version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./gal.xslt:/etc/nginx/gal.xslt:ro
      - ./cache:/var/cache/nginx
#      - /media:/var/www:ro  # set wanted host folder
#      - ./.htpasswd:/etc/.htpasswd:ro